version: 2
jobs:
  build:
    working_directory: /home/circleci/grails-cookie-session
    docker:
      - image: circleci/openjdk:8u141-jdk
    environment:
      - BASH_ENV: /home/circleci/grails-cookie-session/local.env
      - TERM: dumb
      - GRADLE_OPTS: '-Xmx768m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap'
      - GRADLE_USER_HOME: /home/circleci/.gradle

    steps:
      - checkout

      - run:
          name: Configure Gradle Memory
          command: |
            mkdir -p ${GRADLE_USER_HOME}
            echo "org.gradle.jvmargs=-Xmx768m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap" >> ${GRADLE_USER_HOME}/gradle.properties
            echo "org.gradle.daemon=false" >> ${GRADLE_USER_HOME}/gradle.properties

      - run:
          name: Configure Artifact Cache
          command: |
            set -x
            if curl -s -f --connect-timeout=10 http://192.168.1.254:9081/service/local/status; then
              mkdir -p ${GRADLE_USER_HOME}
              cp -v /home/circleci/grails-cookie-session/.circleci/init.gradle ${GRADLE_USER_HOME}/init.gradle
              mkdir -p /home/circleci/grails-cookie-session/.gradle/circleci
              mkdir -p /home/circleci/.m2/
              cp -v /home/circleci/grails-cookie-session/.circleci/settings.xml /home/circleci/.m2/settings.xml
            fi

      - restore_cache:
          keys:
            - v1-code-{{ .Branch }}-{{ checksum "build.gradle" }}
            - v1-code-{{ .Branch }}-

      - run:
          name: Unit Test and Publish for Further Testing
          command: |
            ./gradlew -s publishToMavenLocal

      - run:
          name: Unit Test Grails Versions 3.0-3.3
          command: |
            ./gradlew -s --continue check testAll cloverGenerateReport

      - run:
          name: Integration Test Grails Versions 3.0-3.3
          command: |
            ./gradlew -s --continue integrationTestAll

      - save_cache:
          key: v2-code-{{ .Branch }}-{{ checksum "build.gradle" }}
          paths:
            - /home/circleci/.gradle/native
            - /home/circleci/.gradle/caches
            - /home/circleci/.gradle/nodejs
            - /home/circleci/.gradle/wrapper

      - store_test_results:
          path: ./build/test-results
      - store_test_results:
          path: ./grails3_0/build/test-results
      - store_test_results:
          path: ./grails3_1/build/test-results
      - store_test_results:
          path: ./grails3_2/build/test-results
      - store_test_results:
          path: ./grails3_3/build/test-results

      - store_artifacts:
          path: ./build/reports
          destination: tests
      - store_artifacts:
          path: ./grails3_0/build/reports
          destination: grails-3.0
      - store_artifacts:
          path: ./grails3_1/build/reports
          destination: grails-3.1
      - store_artifacts:
          path: ./grails3_2/build/reports
          destination: grails-3.2
      - store_artifacts:
          path: ./grails3_3/build/reports
          destination: grails-3.3
      - store_artifacts:
          path: ./build/reports/clover
          destination: code_coverage
      - store_artifacts:
          path: ./build/reports/codenarc
          destination: codenarc

      - deploy:
          name: Publish Plugin
          command: |
            set -x
            if [ "${CIRCLE_BRANCH}" == "xmaster" ]; then
              ./gradlew -s publishPlugin
            fi
